In [ ]:
import pandas as pd

path = "data/av2_mf_tiny/train/0000b0f9-99f9-4a1f-a231-5be9e4c523f7/scenario_0000b0f9-99f9-4a1f-a231-5be9e4c523f7.parquet"
df = pd.read_parquet(path)   # 需要 pyarrow
print(df.shape)
print(df.columns)
print(df.head())

(2511, 16)
Index(['observed', 'track_id', 'object_type', 'object_category', 'timestep',
       'position_x', 'position_y', 'heading', 'velocity_x', 'velocity_y',
       'scenario_id', 'start_timestamp', 'end_timestamp', 'num_timestamps',
       'focal_track_id', 'city'],
      dtype='object')
   observed track_id object_type  object_category  timestep  position_x  \
0      True    50513     vehicle                2         0   18.591604
1      True    50513     vehicle                2         1   18.693685
2      True    50513     vehicle                2         2   18.819566
3      True    50513     vehicle                2         3   18.967646
4      True    50513     vehicle                2         4   19.136512

   position_y   heading  velocity_x  velocity_y  \
0 -414.075877  1.269081    1.889325    6.052013
1 -413.747185  1.268987    1.898718    6.062060
2 -413.338909  1.268902    1.902845    6.048986
3 -412.857532  1.268811    1.890446    5.996844
4 -412.309115  1.268704    1.877703    5.958815

                            scenario_id  start_timestamp  end_timestamp  \
0  0000b0f9-99f9-4a1f-a231-5be9e4c523f7     3.159742e+17   3.159742e+17
1  0000b0f9-99f9-4a1f-a231-5be9e4c523f7     3.159742e+17   3.159742e+17
2  0000b0f9-99f9-4a1f-a231-5be9e4c523f7     3.159742e+17   3.159742e+17
3  0000b0f9-99f9-4a1f-a231-5be9e4c523f7     3.159742e+17   3.159742e+17
4  0000b0f9-99f9-4a1f-a231-5be9e4c523f7     3.159742e+17   3.159742e+17

   num_timestamps focal_track_id    city
0             110          51241  austin
1             110          51241  austin
2             110          51241  austin
3             110          51241  austin
4             110          51241  austin

In [2]:
import pandas as pd
import numpy as np
import random
import time
import wandb
import torch
from datasets.Dataset import Dataset
from datasets.InD import InD
from datasets.EthUcy import EthUcy
from model.TrajFlow import TrajFlow, CausalEnocder, Flow
from train import train
from evaluate import evaluate
from visualize import visualize
from visualize_temp import visualize_temp

def load_pz_t1(csv_path, device="cpu", dtype=torch.float32):
    df = pd.read_csv(csv_path)          # shape: (steps*steps, T)
    arr = df.values                     # NumPy array
    pz_t1 = torch.tensor(arr, dtype=dtype, device=device)
    return pz_t1

import matplotlib.pyplot as plt
import numpy as np

def save_heatmap(likelihood, t, output_path, cmap="viridis"):
    plt.figure(figsize=(6,5))
    plt.imshow(likelihood, cmap=cmap, origin="lower")
    plt.colorbar(label="Likelihood")
    plt.title(f"Heatmap at t={t}")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()


pz_t1 = load_pz_t1(f"pz_t1_{5}.csv")
steps = 1000
for t in range(100):
    likelihood = pz_t1[:, t].cpu().numpy().reshape(steps, steps)
    likelihood = likelihood / np.max(likelihood)
    df = pd.DataFrame(likelihood)
    df.to_csv(f"likelihood_{5}_{t}.csv", index=False)


    # Save heatmap
    save_heatmap(likelihood, t, f"heatmap_5_{t}.png")

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4.537533e-18,4.001701e-18,3.521897e-18,3.093313e-18,2.711056e-18,2.497066e-18,2.348480e-18,2.259071e-18,2.170208e-18,2.083306e-18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,3.028639e-18,2.665586e-18,2.341252e-18,2.052197e-18,1.794916e-18,1.657286e-18,1.558682e-18,1.497747e-18,1.436726e-18,1.377969e-18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,2.015800e-18,1.770671e-18,1.552026e-18,1.357766e-18,1.185087e-18,1.096879e-18,1.031705e-18,9.902299e-19,9.485568e-19,9.089287e-19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,1.337889e-18,1.172845e-18,1.025940e-18,8.956260e-19,7.802259e-19,7.239317e-19,6.809379e-19,6.529011e-19,6.244587e-19,5.978458e-19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,8.855935e-19,7.747627e-19,6.764022e-19,5.892532e-19,5.123018e-19,4.765078e-19,4.481827e-19,4.292755e-19,4.099989e-19,3.921831e-19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
pd.read_csv("pz_t1_0.csv")

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
grids = pd.read_csv("denormalized_grid_1.csv")
heatmaps = pd.read_csv("pz_t1_0.csv")

df_av = pd.read_csv("unobserved_traj_1.csv")



grids

           x          y
0       25.0 -65.000000
1       25.0 -64.944945
2       25.0 -64.889890
3       25.0 -64.834835
4       25.0 -64.779780
...      ...        ...
999995  85.0 -10.220220
999996  85.0 -10.165165
999997  85.0 -10.110110
999998  85.0 -10.055055
999999  85.0 -10.000000

[1000000 rows x 2 columns]

In [6]:
df_av

            x          y
0   53.178129  23.132209
1   53.050849  23.103731
2   52.922300  23.074211
3   52.792020  23.042821
4   52.660400  23.009701
..        ...        ...
95  38.071340  11.399589
96  37.860940  11.181968
97  37.647590  10.961040
98  37.431550  10.737201
99  37.212700  10.509949

[100 rows x 2 columns]

In [7]:
# Load grid coordinates and plot a canvas you can overlay trajectories on later
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

df = pd.read_csv("denormalized_grid_1.csv")

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
if len(numeric_cols) >= 2:
    xcol, ycol = numeric_cols[0], numeric_cols[1]
else:
    raise ValueError("Need two numeric columns.")


df1= pd.read_csv("unobserved_traj_5.csv")

df1_known = pd.read_csv("observed_traj_5.csv")
df_av = pd.read_csv("unobserved_traj_2.csv")
df_av_known = pd.read_csv("observed_traj_2.csv")

df["position_x"] = df["x"] 
df["position_y"] = df["y"] 

df_av["position_x"] = df_av["x"] 
df_av["position_y"] = -df_av["y"] 
df1["position_x"] = df1["x"]
df1["position_y"] = -df1["y"]

df_av_known["position_x"] = df_av_known["x"] 
df_av_known["position_y"] = -df_av_known["y"] 
df1_known["position_x"] = df1_known["x"]
df1_known["position_y"] = -df1_known["y"]

# Plot only
plt.figure(figsize=(8,8))
plt.scatter(df["position_x"], df["position_y"], s=0.1)
plt.plot(df_av["position_x"], df_av["position_y"], color = "red", label = "AV (2)")
plt.plot(df_av_known["position_x"], df_av_known["position_y"], color = "pink", label = "AV (2) known")
plt.plot(df1_known["position_x"], df1_known["position_y"], color = "green", label = "Agent (5)_known")
plt.plot(df1["position_x"], df1["position_y"], color = "purple", label = "Agent (5)")
plt.gca().set_aspect('equal', 'box')
plt.xlabel(xcol)
plt.ylabel(ycol)
plt.title("Grid Canvas")
plt.tight_layout()
plt.legend()


plt.savefig("grids.png", dpi=300)

/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91628/3605982648.py:50: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig("grids.png", dpi=300)

In [8]:
#Data_processing
# df_av["position_x"] = df_av["x"] 
# df_av["position_y"] = -df_av["y"] 
# df1["position_x"] = df1["x"]
# df1["position_y"] = -df1["y"]


delta_t = 0.04  # seconds between frames

# ----- Compute velocities for df_av -----
dx = df_av["position_x"].diff()
dy = df_av["position_y"].diff()

df_av["velocity_x"] = dx / delta_t
df_av["velocity_y"] = dy / delta_t

# df_av["velocity_x"].iloc[0] = 0.0
# df_av["velocity_y"].iloc[0] = 0.0

df_av = df_av.iloc[1:].reset_index(drop=True)

# ----- Compute velocities for df1 -----
dx = df1["position_x"].diff()
dy = df1["position_y"].diff()

df1["velocity_x"] = dx / delta_t
df1["velocity_y"] = dy / delta_t

# df1["velocity_x"].iloc[0] = 0.0
# df1["velocity_y"].iloc[0] = 0.0

df1 = df1.iloc[1:].reset_index(drop=True)

In [9]:
# Compute Collision time

# normal vehicle = 5m by 2m: safety box: 10m by 7m
lengths = 5
widths = 2


def calculate_safety_box_av(row):
    car_x = row["position_x"]
    car_y = row["position_y"]
    car_vx = row["velocity_x"]
    car_vy = row["velocity_y"]
    box_length= lengths
    box_width= widths 
    car_angle = np.arctan2(car_vy, car_vx)

    local_corners = np.array([
        [-box_length / 2, -box_width / 2],
        [-box_length / 2, box_width / 2],
        [box_length / 2, box_width / 2],
        [box_length / 2, -box_width / 2],
        [-box_length / 2, -box_width / 2]# Repeat the first point to close the box
    ])
    rotation_matrix = np.array([
        [np.cos(car_angle), -np.sin(car_angle)],
        [np.sin(car_angle), np.cos(car_angle)]
    ])
    global_corners = local_corners.dot(rotation_matrix) + np.array([car_x, car_y])
    global_corners[:, 1] = -global_corners[:, 1] + 2 * car_y
    return global_corners

def calculate_safety_box(row):
    car_x = row["position_x"]
    car_y = row["position_y"]
    car_vx = row["velocity_x"]
    car_vy = row["velocity_y"]
    box_length= lengths
    box_width= widths

    car_angle = np.arctan2(car_vy, car_vx)

    local_corners = np.array([
        [-box_length / 2, -box_width / 2],
        [-box_length / 2, box_width / 2],
        [box_length / 2, box_width / 2],
        [box_length / 2, -box_width / 2],
        [-box_length / 2, -box_width / 2]# Repeat the first point to close the box
    ])
    rotation_matrix = np.array([
        [np.cos(car_angle), -np.sin(car_angle)],
        [np.sin(car_angle), np.cos(car_angle)]
    ])
    global_corners = local_corners.dot(rotation_matrix) + np.array([car_x, car_y])
    global_corners[:, 1] = -global_corners[:, 1] + 2 * car_y
    return global_corners

df_av["corners"] = df_av.apply(lambda x: calculate_safety_box_av(x), axis = 1)
df1["corners"] = df1.apply(lambda x: calculate_safety_box(x), axis = 1)

df_av1 = df_av
df11 = df1

In [10]:
import matplotlib.pyplot as plt

t = 3
plt.plot(df_av.iloc[t]["corners"][:, 0], df_av.iloc[t]["corners"][:, 1], '-o')  # Plot the corners
plt.scatter(df_av.iloc[t]["position_x"], df_av.iloc[t]["position_y"], color='red')  # Mark the car's position
plt.plot(df1.iloc[t]["corners"][:, 0], df1.iloc[t]["corners"][:, 1], '-o')  # Plot the corners
plt.scatter(df1.iloc[t]["position_x"], df1.iloc[t]["position_y"], color='red')  # Mark the car's position

plt.xlabel('X Coordinate')
plt.ylabel('Y Coordinate')
plt.title('Safety Box around the Car')
plt.grid(True)
plt.axis('equal')
plt.savefig("boxes.png", dpi=300)

/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91628/797829322.py:14: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  plt.savefig("boxes.png", dpi=300)

In [11]:
#check global vs focal
from matplotlib.path import Path
import pandas as pd
import numpy as np
import matplotlib.patches as patches
from shapely.geometry import Polygon, Point
import time
import math
from matplotlib import cm


import matplotlib.pyplot as plt
import numpy as np

overall_heatmap = pd.DataFrame()
for t in range(len(df1)):
    lik = pd.read_csv(f"likelihood_5_{t}.csv")
    data_cut = pd.read_csv("denormalized_grid_1.csv")
    # ---- Fix: remove the incorrect first row ----
    #lik = lik.iloc[1:, :]

    # ---- Reshape likelihood to match the grid ----
    lik_long = lik.to_numpy().reshape(-1)

    # ---- Check size matches ----
    if len(data_cut) != len(lik_long):
        raise ValueError(f"Size mismatch: grid={len(data_cut)}, likelihood={len(lik_long)}")

    # ---- Attach probability column ----
    data_cut["score"] = lik_long

    overall_heatmap = pd.concat([overall_heatmap,data_cut])

# overall_heatmap["score2"] = overall_heatmap["score"] - np.min(overall_heatmap["score"].values)

In [16]:
# Load files
lik = pd.read_csv("likelihood_5_3.csv")
data_cut = pd.read_csv("denormalized_grid_1.csv")

# ---- Fix: remove the incorrect first row ----
# lik = lik.iloc[1:, :]

# ---- Reshape likelihood to match the grid ----
lik_long = lik.to_numpy().reshape(-1)

# ---- Check size matches ----
if len(data_cut) != len(lik_long):
    raise ValueError(f"Size mismatch: grid={len(data_cut)}, likelihood={len(lik_long)}")

# ---- Attach probability column ----
data_cut["score"] = lik_long


# Prepare data for heatmap
# data_cut = data[(data["position_x"] >= minx) &(data["position_x"] <= maxx+ 1)& (data["position_y"] >= miny)& (data["position_y"] <= maxy+ 1)]
x = data_cut['x']
y = data_cut['y']
score = data_cut['score']
# Generate a heatmap
plt.figure(figsize=(10, 8))
hb = plt.scatter(x, y, c=score, cmap=cm.RdYlGn_r)
cb = plt.colorbar(hb)
cb.set_label('mean score')

t =3
plt.plot(df_av["position_x"], df_av["position_y"], color = "red", label = "AV (2)")
plt.plot(df_av_known["position_x"], df_av_known["position_y"], color = "pink", label = "AV (2) known")
plt.plot(df1_known["position_x"], df1_known["position_y"], color = "green", label = "Agent (5)_known")
plt.plot(df1["position_x"], df1["position_y"], color = "purple", label = "Agent (5)")

plt.plot(df_av.iloc[t]["corners"][:, 0], df_av.iloc[t]["corners"][:, 1], '-o')  # Plot the corners
plt.scatter(df_av.iloc[t]["position_x"], df_av.iloc[t]["position_y"], color='red')  # Mark the car's position
plt.plot(df1.iloc[t]["corners"][:, 0], df1.iloc[t]["corners"][:, 1], '-o')  # Plot the corners
plt.scatter(df1.iloc[t]["position_x"], df1.iloc[t]["position_y"], color='red')  # Mark the car's position

plt.xlabel('X coordinate')
plt.ylabel('Y coordinate')
plt.title('Heatmap based on score value')
plt.tight_layout()
plt.savefig("heatmaps_score.png", dpi=300)



plt.show()

/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91628/3196252402.py:49: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.path import Path

# Hard Coding...
# Assuming df_av and df11 are defined elsewhere in your script
# just for generating the heat_map_test
import time

start_time = time.time()

minx = np.floor(np.min(df_av1["position_x"])-20)-0.05
miny = np.floor(np.min(df_av1["position_y"])-20)-0.05
maxx = np.ceil(np.max(df_av1["position_x"])+20)-0.05
maxy = np.ceil(np.max(df_av1["position_y"])+20)-0.05

print(minx,miny,maxx,maxy)# 2816.0 -1976.0 2844.0 -1953.0

# Define the function for calculating the safety box
def calculate_safety_box(car_x, car_y, car_vx, car_vy, car_angle, box_length, box_width):
    #car_angle = np.arctan2(car_vy, car_vx)
    local_corners = np.array([
        [-box_length / 2, -box_width / 2],
        [-box_length / 2, box_width / 2],
        [box_length / 2, box_width / 2],
        [box_length / 2, -box_width / 2],
        [-box_length / 2, -box_width / 2]  # Repeat the first point to close the box
    ])
    rotation_matrix = np.array([
        [np.cos(car_angle), -np.sin(car_angle)],
        [np.sin(car_angle), np.cos(car_angle)]
    ])
    global_corners = local_corners.dot(rotation_matrix) + np.array([car_x, car_y])
    global_corners[:, 1] = -global_corners[:, 1] + 2 * car_y
    return global_corners

# Optimized function to check if points are inside the box
def is_inside_box_optimized(x_range, y_range, box_corners):
    X, Y = np.meshgrid(x_range, y_range)
    points = np.vstack([X.ravel(), Y.ravel()]).T
    box_path = Path(box_corners)
    grid_inside = box_path.contains_points(points)
    inside_mask = grid_inside.reshape(X.shape)
    return inside_mask.astype(int)

# Function to create the heatmap dataframe
def create_heatmap_dataframe(min_x, max_x, min_y, max_y, box_corners, t, heatmap_data=None):
    x_range = np.arange(min_x, max_x + 1, 0.1)
    y_range = np.arange(min_y, max_y + 1, 0.1)
    x_range = np.round(x_range, 1)
    y_range = np.round(y_range, 1)

    # if t == 0:
    #     inside_mask = is_inside_box_optimized(x_range, y_range, box_corners)
    #     heatmap_df = pd.DataFrame(inside_mask, index=y_range, columns=x_range)
    # else:
    heatmap_df = pd.DataFrame(index=y_range, columns=x_range).fillna(0)
    if heatmap_data is not None:
        heatmap_data_valid = heatmap_data[heatmap_data["prob"] != 0]
        print(len(heatmap_data_valid))
        heatmap_data_valid = heatmap_data_valid[(heatmap_data_valid["position_x"]>= min_x-0.5)&(heatmap_data_valid["position_x"]<= max_x+1.5)&(heatmap_data_valid["position_y"] >= min_y-0.5)&(heatmap_data_valid["position_y"]<= max_y+1.5)]
        print(len(heatmap_data_valid))
        heatmap_data_valid = heatmap_data_valid.sort_values("prob")
        heatmap_data_valid = heatmap_data_valid.reset_index(drop=True)
        for _, row in heatmap_data_valid.iterrows():
            x, y, prob = row["position_x"], row["position_y"], row["prob"]
            # This is important (maybe use of meshgrid or polygon make it faster)
            for x_adj in np.arange(x-0.5,x+0.6,0.1):
                for y_adj in np.arange(y-0.5,y+0.6,0.1):
                    if np.round(y_adj,1) in y_range and np.round(x_adj,1) in x_range:
                        heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob

                #if x in x_range and y in y_range:
                #    heatmap_df.at[y, x] = prob
    return heatmap_df

#check global vs focal
from matplotlib.path import Path
import pandas as pd
import numpy as np
import matplotlib.patches as patches
from shapely.geometry import Polygon, Point
import time
import math
from matplotlib import cm


import matplotlib.pyplot as plt
import numpy as np

overall_heatmap = pd.DataFrame()
for t in range(len(df1)):
    lik = pd.read_csv(f"likelihood_5_{t}.csv")
    data_cut = pd.read_csv("denormalized_grid_1.csv")
    # ---- Fix: remove the incorrect first row ----
    #lik = lik.iloc[1:, :]

    # ---- Reshape likelihood to match the grid ----
    lik_long = lik.to_numpy().reshape(-1)

    # ---- Check size matches ----
    if len(data_cut) != len(lik_long):
        raise ValueError(f"Size mismatch: grid={len(data_cut)}, likelihood={len(lik_long)}")

    # ---- Attach probability column ----
    data_cut["score"] = lik_long

    overall_heatmap = pd.concat([overall_heatmap,data_cut])

# overall_heatmap["score2"] = overall_heatmap["score"] - np.min(overall_heatmap["score"].values)


#print(np.min(overall_heatmap["score"].values))
#print(np.max(overall_heatmap["score2"].values))

for t in range(len(df1)):
    lik = pd.read_csv(f"likelihood_5_{t}.csv")
    heatmap_data = pd.read_csv("denormalized_grid_1.csv")
    # ---- Fix: remove the incorrect first row ----
    #lik = lik.iloc[1:, :]

    # ---- Reshape likelihood to match the grid ----
    lik_long = lik.to_numpy().reshape(-1)

    # ---- Check size matches ----
    if len(data_cut) != len(lik_long):
        raise ValueError(f"Size mismatch: grid={len(data_cut)}, likelihood={len(lik_long)}")

    # ---- Attach probability column ----
    heatmap_data["score"] = lik_long

    #heatmap_data["score2"] = heatmap_data["score"] - np.min(heatmap_data["score"].values)
    #heatmap_data["prob"] = heatmap_data["score2"] / np.max(heatmap_data["score2"].values)
    #print(np.min(heatmap_data["score"].values))
    #print(np.max(heatmap_data["score2"].values))

    heatmap_data["score2"] = heatmap_data["score"]# - np.min(overall_heatmap["score"].values)
    heatmap_data["prob"] = heatmap_data["score2"] #/ np.max(overall_heatmap["score2"].values)
    heatmap_data["position_x"] = heatmap_data["x"]
    heatmap_data["position_y"] = heatmap_data["y"]
    #heatmap_data["prob"] = heatmap_data["score"] # if/as it is scaled between 0 and 1

    heatmap_data.to_csv(f"heatmap_test_prob{t}.csv")
        #print(np.max(heatmap_data["prob"]))

    box_length = lengths #lengths[df11.iloc[0]["object_type"]]
    box_width = widths #widths[df11.iloc[0]["object_type"]]


    car_position = (df11.iloc[t]["position_x"], df11.iloc[t]["position_y"])  # x, y
    car_velocity = (df11.iloc[t]["velocity_x"], df11.iloc[t]["velocity_y"])  # vx, vy
    # this is needed for the t=0 heatmap
    car_angle = np.arctan2(df11.iloc[t]["velocity_y"], df11.iloc[t]["velocity_x"])

    overall_heatmap = pd.DataFrame()




    safety_box_corners = calculate_safety_box(*car_position, *car_velocity, car_angle,box_length, box_width)

    #plt.plot(safety_box_corners[:, 0], safety_box_corners[:, 1], '-o')  # Plot the corners
    #plt.scatter(car_position[0], car_position[1], color='red')  # Mark the car's position
    #plt.xlabel('X Coordinate')
    #plt.ylabel('Y Coordinate')
    #plt.title('Safety Box around the Car')
    #plt.grid(True)
    #plt.axis('equal')

    heatmap_df = create_heatmap_dataframe(minx, maxx, miny, maxy, safety_box_corners, t, heatmap_data)
    #heatmap_df.to_csv(f"heatmap_testh_dbg{t}.csv")
    # print(np.max(np.reshape(heatmap_df.to_numpy(),heatmap_df.shape[0]*heatmap_df.shape[1])))
    # print(np.min(np.reshape(heatmap_df.to_numpy(),heatmap_df.shape[0]*heatmap_df.shape[1])))

    heatmap_df.to_csv(f"heatmap_testh{t}.csv")

35.95 -60.05 79.95 -5.05

/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:59: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  heatmap_df = pd.DataFrame(index=y_range, columns=x_range).fillna(0)
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob

85940
83873

/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob
/var/folders/70/7hwsprrj2xb232_my0td8xnr0000gn/T/ipykernel_91409/2700788095.py:73: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.0000000000000001e-45' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  heatmap_df.at[np.round(y_adj,1), np.round(x_adj,1)] = prob

KeyboardInterrupt:

In [15]:
# Preload all CSV files into a dictionary if the dataset is not too large
heatmap_files = [f"heatmap_testh{i}.csv" for i in range(len(df1))]
heatmap_data = {i: pd.read_csv(file) for i, file in enumerate(heatmap_files)}

In [16]:
def load_heatmap(time):
    # Use ceiling for non-integer times, but keep integers as is
    #key = int(math.ceil(time)) if not time.is_integer() else int(time)
    # Limit the key to a maximum of 6
    return heatmap_data[time]

def calculate_safety_box(car_x, car_y, car_vx, car_vy, car_angle, box_length, box_width):
    #car_angle = np.arctan2(car_vy, car_vx)
    local_corners = np.array([
        [-box_length / 2, -box_width / 2],
        [-box_length / 2, box_width / 2],
        [box_length / 2, box_width / 2],
        [box_length / 2, -box_width / 2],
        [-box_length / 2, -box_width / 2]
    ])
    rotation_matrix = np.array([
        [np.cos(car_angle), -np.sin(car_angle)],
        [np.sin(car_angle), np.cos(car_angle)]
    ])
    global_corners = local_corners.dot(rotation_matrix) + np.array([car_x, car_y])
    global_corners[:, 1] = -global_corners[:, 1] + 2 * car_y
    return global_corners

def create_safety_box_grid_dict(corners, resolution_length, resolution_width):
    """ Create a grid of points within the safety box defined by corners and return a dictionary of their global coordinates. """
    top_edge = interpolate_points(corners[0], corners[1], resolution_length)
    bottom_edge = interpolate_points(corners[3], corners[2], resolution_length)

    grid_dict = {}
    for i in range(resolution_length):
        vertical_line = interpolate_points(top_edge[i], bottom_edge[i], resolution_width)
        for j, point in enumerate(vertical_line):
            grid_dict[(i, j)] = point

    return grid_dict

def interpolate_points(start, end, num_points):
    return np.linspace(start, end, num_points, endpoint=True)


def create_safety_box_grid(corners, resolution_length, resolution_width):
    """ Create a grid of points within the safety box defined by corners. """
    top_edge = np.linspace(corners[0], corners[1], resolution_length)
    bottom_edge = np.linspace(corners[3], corners[2], resolution_length)
    grid_x, grid_y = np.meshgrid(top_edge, bottom_edge)
    grid = np.dstack((grid_x, grid_y)).reshape(-1, 2)
    return grid


def create_safety_box_array(corners, resolution_length, resolution_width):
    """ Create an array for the safety box where each cell contains its global coordinates. """
    top_edge = interpolate_points(corners[0], corners[3], resolution_length)
    bottom_edge = interpolate_points(corners[1], corners[2], resolution_length)

    safety_box_array = np.zeros((resolution_width, resolution_length), dtype=object)

    for i in range(resolution_length):
        vertical_line = interpolate_points(top_edge[i], bottom_edge[i], resolution_width)
        for j, point in enumerate(vertical_line):
            safety_box_array[j, i] = point

    return safety_box_array

# need to store the information about the position of the grid in terms of the center location



# get the distance from the point representing the cell and the car position

def create_safety_box_array_distance_to_center(corners, resolution_length, resolution_width,car_x, car_y):
    """ Create an array for the safety box where each cell contains its global coordinates. """
    top_edge = interpolate_points(corners[0], corners[3], resolution_length)
    bottom_edge = interpolate_points(corners[1], corners[2], resolution_length)

    safety_box_array = np.zeros((resolution_width, resolution_length), dtype=object)

    for i in range(resolution_length):
        vertical_line = interpolate_points(top_edge[i], bottom_edge[i], resolution_width)
        for j, point in enumerate(vertical_line):
            safety_box_array[j, i] = np.sqrt((point[0]-car_x)**2+(point[1]-car_y)**2)

    return safety_box_array


def fill_safety_box_with_occupancy(heatmap, car_x, car_y, car_vx, car_vy, car_angle, box_length=30, box_width=28, resolution=1):
    # NEED THE SAFETY BOX DIMENSION BASED ON THE types of vehicles (ego and agent)
    # normal vehicle = 5m by 2m: safety box: 10m by 7m

    #bl = 10
    #bw = 7



    # Dynamically changing safety box - based on the ego's velocity
    # either we can consider the stoppping distance
    # or we can consider the current speed * 0.1s -> m (maximum moving distance of ego vehicle within timestep)
    # I think the second approach make sense.

    # steps of the dynamically changing safety box
    # 1. calculate the velocity in the direction of the heading
    # 2. Then multiply to 0.1s to get the max traveling distance.

    # Lets just use the max velocity of the ego vehicle
    #https://www.omnicalculator.com/physics/stopping-distance
    car_v_max = np.sqrt(car_vx**2+car_vy**2) #m/s
    # dynamic_extension = car_v_max * 0.1  max traveling distance too small

    # s – Stopping distance in meters;
    #t – Perception-reaction time in seconds;
    #v – Speed of the car in km/h;
    #G – Grade (slope) of the road, expressed as a decimal. Positive for an uphill grade and negative for a downhill road; and
    #f – Coefficient of friction between the tires and the road. It is assumed to be 0.7 on a dry road and between 0.3 and 0.4 on a wet road.

    stop_d = (0.278 * 1.5 * 3.6*car_v_max) + (3.6*car_v_max)**2 / (254 * (0.5 + 0))

    # extra = max(lengths[df11.iloc[0]["object_type"]], widths[df11.iloc[0]["object_type"]])
    # bl = lengths[df_av1.iloc[0]["object_type"]]+ extra + stop_d*2
    # bw = widths[df_av1.iloc[0]["object_type"]]+ extra

    extra = max(lengths, widths)
    bl = lengths + extra +stop_d*2 #lengths[df_av1.iloc[0]["object_type"]]+ extra
    bw = lengths + extra #widths[df_av1.iloc[0]["object_type"]]+ extra


    print(bl)
    # adjustment only on the forward

    resolution = 0.1 #0.01

    corners = calculate_safety_box(car_x, car_y, car_vx, car_vy, car_angle, bl, bw)
    resolution_length = math.ceil(bl/resolution)#int(bl/resolution)  # Number of points along the box's length
    resolution_width = math.ceil(bw/resolution) # Number of points along the box's width

    print(resolution_length)

    safety_box_array = create_safety_box_array(corners, resolution_length, resolution_width)
    safety_box_df = pd.DataFrame(safety_box_array)
    print(safety_box_array.shape)

    #safety_box_array_distance = create_safety_box_array_distance_to_center(corners, resolution_length, resolution_width,car_x, car_y)
    #safety_box_df_distance = pd.DataFrame(safety_box_array_distance)

    return corners,safety_box_array, safety_box_df#,safety_box_array_distance,safety_box_df_distance

def fill_safety_box_with_occupancy_og(heatmap, car_x, car_y, car_vx, car_vy, car_angle, box_length=30, box_width=28, resolution=1):
    # NEED THE SAFETY BOX DIMENSION BASED ON THE types of vehicles (ego and agent)
    # normal vehicle = 5m by 2m: safety box: 10m by 7m

    #bl = 10
    #bw = 7


    # original safety box

    #extra = max(lengths[df11.iloc[0]["object_type"]], widths[df11.iloc[0]["object_type"]])
    extra = max(lengths, widths)
    bl = lengths + extra #lengths[df_av1.iloc[0]["object_type"]]+ extra
    bw = lengths + extra #widths[df_av1.iloc[0]["object_type"]]+ extra

    # adjustment only on the forward

    resolution = 0.1 #0.01

    corners = calculate_safety_box(car_x, car_y, car_vx, car_vy, car_angle, bl, bw)
    resolution_length = math.ceil(bl/resolution)#int(bl/resolution)  # Number of points along the box's length
    resolution_width = math.ceil(bw/resolution) # Number of points along the box's width

    safety_box_array = create_safety_box_array(corners, resolution_length, resolution_width)
    safety_box_df = pd.DataFrame(safety_box_array)
    print(safety_box_array.shape)

    #safety_box_array_distance = create_safety_box_array_distance_to_center(corners, resolution_length, resolution_width,car_x, car_y)
    #safety_box_df_distance = pd.DataFrame(safety_box_array_distance)

    return corners,safety_box_array, safety_box_df #,safety_box_array_distance,safety_box_df_distance

# Need to optimize this part
def fill_safety_box_with_heatmap_values(safety_box_array, heatmapf, t):
    t = round(t, 1)
    filled_safety_box = np.zeros_like(safety_box_array, dtype=float)
    heatmap = heatmapf.copy()
    # Assume the first column of heatmap is 'Unnamed: 0', which we will use as the index
    heatmap.index = heatmap["Unnamed: 0"]
    heatmap.drop(columns=["Unnamed: 0"], inplace=True)

    # Convert the column names and index to numeric types for comparison
    heatmap.columns = pd.to_numeric(heatmap.columns)
    heatmap.index = pd.to_numeric(heatmap.index)

    # Iterate through each cell in the safety box grid
    for i in range(safety_box_array.shape[0]):
        for j in range(safety_box_array.shape[1]):
            x, y = safety_box_array[i, j]

            # Check if the point falls within any cell in the heatmap
            x_mask = (heatmap.columns >= x - 0.05) & (heatmap.columns <= x + 0.05)
            y_mask = (heatmap.index >= y - 0.05) & (heatmap.index <= y + 0.05)

            # If the point is within the range, assign the corresponding heatmap value
            #hm_values = heatmap.loc[y_mask, x_mask].values[0]
            #hm_values = list(hm_values)
            #hm_values.append(0)
            #hm_values = np.array(hm_values)
            #filled_safety_box[i, j] = np.max(hm_values)
            if x_mask.any() and y_mask.any():
                hm_values = heatmap.loc[y_mask, x_mask]
                filled_safety_box[i, j] = hm_values.values.max()

    return filled_safety_box


import numpy as np
import pandas as pd
from matplotlib.path import Path

def is_inside_box_optimized(x_range, y_range, box_corners):
    X, Y = np.meshgrid(x_range, y_range)
    points = np.vstack([X.ravel(), Y.ravel()]).T
    box_path = Path(box_corners)
    grid_inside = box_path.contains_points(points)
    inside_mask = grid_inside.reshape(X.shape)
    return inside_mask.astype(int)

def create_heatmap_dataframe(min_x, max_x, min_y, max_y, box_corners):
    # Define the range of coordinates with a step of 1 meter
    x_range = np.arange(min_x, max_x + 1, 0.1)
    y_range = np.arange(min_y, max_y + 1, 0.1)

    # Use the optimized function to check if points are inside the box
    inside_mask = is_inside_box_optimized(x_range, y_range, box_corners)

    # Create a DataFrame from the mask
    heatmap_df = pd.DataFrame(inside_mask, index=np.round(y_range, 1), columns=np.round(x_range, 1))

    heatmap_df

    return heatmap_df

In [17]:

time_series = [] # just the maximum safetybox
time_series_each = [] # dynamical safety box
time_series_og = []

# just for generating the heat_map_test

minx = np.floor(np.min(df_av1["position_x"])-20)-0.05
miny = np.floor(np.min(df_av1["position_y"])-20)-0.05
maxx = np.ceil(np.max(df_av1["position_x"])+20)-0.05
maxy = np.ceil(np.max(df_av1["position_y"])+20)-0.05

print(minx,miny,maxx,maxy)# 2816.0 -1976.0 2844.0 -1953.0

for time in range(len(df1)):
    print(time)
    #print(int(time))
    ego_vehicle_position = (df_av1.iloc[int(time)]["position_x"], df_av1.iloc[int(time)]["position_y"])
    ego_vehicle_velocity = (df_av1.iloc[int(time)]["velocity_x"], df_av1.iloc[int(time)]["velocity_y"])
    ego_vehicle_car_angle = np.arctan2(df_av1.iloc[int(time)]["velocity_y"], df_av1.iloc[int(time)]["velocity_x"])# df_av1.iloc[int(time)]["heading"]
    heatmap = load_heatmap(time)  # Access preloaded heatmap
    #safety_box_corners_large, safety_box_array, safety_box_df,safety_box_array_distance, safety_box_df_distance = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity,ego_vehicle_car_angle)

    # original safety box
    safety_box_corners_large_og, safety_box_array_og, safety_box_df_og = fill_safety_box_with_occupancy_og(heatmap, *ego_vehicle_position, *ego_vehicle_velocity,ego_vehicle_car_angle)

    filled_safety_box_og = fill_safety_box_with_heatmap_values(safety_box_array_og, heatmap,time)

    # Convert to DataFrame for visualization (optional)
    filled_safety_box_og_df = pd.DataFrame(filled_safety_box_og)

    time_series_og.append(np.rot90(filled_safety_box_og))



    #dynamical safety box
    safety_box_corners_large, safety_box_array, safety_box_df = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity,ego_vehicle_car_angle)


    # maximum dynamical safety box  # Max safety_box based on the max velocity within the planned trajectory
    ego_vehicle_velocity_max = (np.max(abs(df_av1["velocity_x"])), np.max(abs(df_av1["velocity_y"])))
    #safety_box_corners_large_max, safety_box_array_max, safety_box_df_max,safety_box_array_distance_max, safety_box_df_distance_max = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity_max,ego_vehicle_car_angle)
    safety_box_corners_large_max, safety_box_array_max, safety_box_df_max = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity_max,ego_vehicle_car_angle)

    
    # add the maximum for now
    filled_safety_box = fill_safety_box_with_heatmap_values(safety_box_array_max, heatmap,time)
    # Convert to DataFrame for visualization (optional)
    filled_safety_box_df = pd.DataFrame(filled_safety_box)

    time_series.append(np.rot90(filled_safety_box))


    # PLOT START HERE

    # Example usage
    t = time

    car_position_av = (df_av1.iloc[int(t)]["position_x"], df_av1.iloc[int(t)]["position_y"]) #x,y
    car_velocity_av = (df_av1.iloc[int(t)]["velocity_x"], df_av1.iloc[int(t)]["velocity_y"]) #x,y
    car_angle_av = np.arctan2(df_av1.iloc[int(t)]["velocity_y"], df_av1.iloc[int(t)]["velocity_x"])# df_av1.iloc[int(time)]["heading"]
    box_length = lengths #lengths[df_av1.iloc[0]["object_type"]]
    box_width = widths #widths[df_av1.iloc[0]["object_type"]]

    fig, ax = plt.subplots(figsize=(8, 6))

    safety_box_corners_av = calculate_safety_box(*car_position_av, *car_velocity_av, car_angle_av,box_length,box_width)
    #plt.plot(safety_box_corners[:, 0], safety_box_corners[:, 1], '-o',color='pink')  # Plot the corners
    #plt.scatter(car_position[0],car_position[1], color='red')  # Mark the car's position

    ax.plot(safety_box_corners_av[:, 0], safety_box_corners_av[:, 1], '-o', color="magenta")
    ax.plot(safety_box_corners_large_og[:, 0], safety_box_corners_large_og[:, 1], '-o', color="blue")

    dynamic_safety_box_all = safety_box_array[:,int((-safety_box_array_og.shape[1]+safety_box_array.shape[1])/2):]
    dynamic_safety_box_all_large = np.array([dynamic_safety_box_all[0][0], dynamic_safety_box_all[-1][0], dynamic_safety_box_all[-1][-1], dynamic_safety_box_all[0][-1],dynamic_safety_box_all[0][0]])
    # Need to check if it applies for all cases..
    ax.plot(dynamic_safety_box_all_large[:, 0], dynamic_safety_box_all_large[:, 1], '-o', color="cyan")
    ax.scatter(car_position_av[0], car_position_av[1], color='black')  # Mark the car's position

    # Set labels, title, limits, and grid
    ax.set_xlabel('X Coordinate')
    ax.set_ylabel('Y Coordinate')
    ax.set_title('Safety Box around the Car')
    # ax.set_xlim(minx, maxx)
    # ax.set_ylim(miny, maxy)
    ax.grid(True)
    #plt.axis('equal')
    # ax = plt.gca()  # Get current axis
    # ax.set_aspect('equal', adjustable='box')
    


    ##### ACTUAL SAFETY BOX AT EACH TIME STEP####
    heatmap_df = create_heatmap_dataframe(minx, maxx, miny, maxy, safety_box_corners_large) #(minx,maxx,miny,maxy)
    #print(heatmap_df)
    x_coords = []
    y_coords = []
    x_coords_check = []
    y_coords_check = []
    weights = []
    checks = []

    #filled_safety_box_df is based on the maximum
    #actual_heat_map_safety_box = safety_box_array_max[:,int((-safety_box_array_og.shape[1]+safety_box_array_max.shape[1])/2): int((-safety_box_array_max.shape[1]+safety_box_array.shape[1])/2)]
    
    actual_heat_map_safety_box = safety_box_array_max[:,int((-safety_box_array_og.shape[1]+safety_box_array_max.shape[1])/2): int((-safety_box_array_max.shape[1]+safety_box_array.shape[1])/2)-1]
    actual_heat_map_safety_box_df = pd.DataFrame(actual_heat_map_safety_box)
    # add the maximum for now

    print(int((-safety_box_array_og.shape[1]+safety_box_array_max.shape[1])/2))
    print(int((-safety_box_array_max.shape[1]+safety_box_array.shape[1])/2))
    print(actual_heat_map_safety_box)
    filled_safety_box_actual = fill_safety_box_with_heatmap_values(actual_heat_map_safety_box, heatmap,time)

    # Convert to DataFrame for visualization (optional)
    filled_safety_box_actual_df = pd.DataFrame(filled_safety_box_actual)

    time_series_each.append(np.rot90(filled_safety_box_actual))

    for col in actual_heat_map_safety_box_df.columns:
        for i in range(len(actual_heat_map_safety_box_df[col])):
            cell = actual_heat_map_safety_box_df[col][i]
            #if filled_safety_box_df[col][i] !=0:
            # Safely evaluate the string as a list
            x_coords.append(cell[0])
            y_coords.append(cell[1])
            weights.append(filled_safety_box_actual_df[col][i])
            if filled_safety_box_actual_df[col][i] !=0:
              x_coords_check.append(cell[0])
              y_coords_check.append(cell[1])
              checks.append(filled_safety_box_actual_df[col][i])

    cmap = plt.cm.RdYlGn_r

    from matplotlib.colors import Normalize
    from matplotlib.cm import ScalarMappable


    # Define the normalization based on the range of values from all datasets
    norm = Normalize(vmin=0, vmax=1)

    # Create a ScalarMappable for consistent color mapping
    sm = ScalarMappable(norm=norm, cmap=cmap)

      # Use subplots to explicitly create a figure and axes
    sc = ax.scatter(x_coords, y_coords, c=sm.to_rgba(weights), alpha=0.3)
    # Create a colorbar with a reference to the Axes and the ScalarMappable


    #print(np.max(weights))

    #print(np.min(weights))
    #print(len(checks))

    plt.colorbar(sm, ax=ax, label='Value')  # Explicitly pass the Axes object here

    plt.savefig('scenario'+str(round(t,1))+'.png')
    plt.close()

    plt.figure()
    plt.scatter(x_coords_check, y_coords_check, c=checks,cmap = cm.RdYlGn_r)
    plt.savefig('scenario_check'+str(round(t,1))+'.png')
    plt.close()
    # PLOT END HERE

35.95 -60.05 79.95 -5.05
0
(100, 100)
11.985315538192722
120
(100, 120)
33.79072413529735
338
(100, 338)
119
-109
[[array([ 65.15027892, -24.8214739 ]) array([ 65.08788586, -24.89996608])
  array([ 65.02549281, -24.97845825]) ...
  array([ 58.53661487, -33.14164417]) array([ 58.47422181, -33.22013634])
  array([ 58.41182875, -33.29862851])]
 [array([ 65.07120677, -24.75861982]) array([ 65.00881371, -24.837112  ])
  array([ 64.94642066, -24.91560417]) ...
  array([ 58.45754271, -33.07879009]) array([ 58.39514966, -33.15728226])
  array([ 58.3327566 , -33.23577443])]
 [array([ 64.99213462, -24.69576574]) array([ 64.92974156, -24.77425792])
  array([ 64.8673485 , -24.85275009]) ...
  array([ 58.37847056, -33.01593601]) array([ 58.31607751, -33.09442818])
  array([ 58.25368445, -33.17292035])]
 ...
 [array([ 57.48028022, -18.72462815]) array([ 57.41788717, -18.80312033])
  array([ 57.35549411, -18.8816125 ]) ...
  array([ 50.86661617, -27.04479842]) array([ 50.80422311, -27.12329059])
  array([ 50.74183005, -27.20178276])]
 [array([ 57.40120807, -18.66177407]) array([ 57.33881501, -18.74026625])
  array([ 57.27642196, -18.81875842]) ...
  array([ 50.78754402, -26.98194434]) array([ 50.72515096, -27.06043651])
  array([ 50.6627579 , -27.13892868])]
 [array([ 57.32213592, -18.59891999]) array([ 57.25974286, -18.67741217])
  array([ 57.19734981, -18.75590434]) ...
  array([ 50.70847186, -26.91909026]) array([ 50.64607881, -26.99758243])
  array([ 50.58368575, -27.0760746 ])]]
1
(100, 100)
12.165318486700079
122
(100, 122)
33.79072413529735
338
(100, 338)
119
-108
[[array([ 65.12828615, -24.79935433]) array([ 65.06638543, -24.87823535])
  array([ 65.00448471, -24.95711637]) ...
  array([ 58.50490897, -33.23962352]) array([ 58.44300825, -33.31850454])
  array([ 58.38110752, -33.39738556])]
 [array([ 65.04882228, -24.73699622]) array([ 64.98692156, -24.81587724])
  array([ 64.92502083, -24.89475826]) ...
  array([ 58.42544509, -33.17726541]) array([ 58.36354437, -33.25614643])
  array([ 58.30164365, -33.33502745])]
 [array([ 64.9693584 , -24.67463811]) array([ 64.90745768, -24.75351913])
  array([ 64.84555696, -24.83240015]) ...
  array([ 58.34598122, -33.1149073 ]) array([ 58.2840805 , -33.19378832])
  array([ 58.22217978, -33.27266934])]
 ...
 [array([ 57.42029048, -18.75061802]) array([ 57.35838976, -18.82949904])
  array([ 57.29648904, -18.90838006]) ...
  array([ 50.7969133 , -27.19088721]) array([ 50.73501257, -27.26976823])
  array([ 50.67311185, -27.34864925])]
 [array([ 57.34082661, -18.68825992]) array([ 57.27892588, -18.76714094])
  array([ 57.21702516, -18.84602196]) ...
  array([ 50.71744942, -27.12852911]) array([ 50.6555487 , -27.20741013])
  array([ 50.59364798, -27.28629115])]
 [array([ 57.26136273, -18.62590181]) array([ 57.19946201, -18.70478283])
  array([ 57.13756129, -18.78366385]) ...
  array([ 50.63798555, -27.066171  ]) array([ 50.57608483, -27.14505202])
  array([ 50.51418411, -27.22393304])]]
2
(100, 100)
12.353613885764991
124
(100, 124)
33.79072413529735
338
(100, 338)
119
-107
[[array([ 65.10239655, -24.75977597]) array([ 65.0412114 , -24.83921332])
  array([ 64.98002626, -24.91865067]) ...
  array([ 58.49440091, -33.33900989]) array([ 58.43321577, -33.41844724])
  array([ 58.37203062, -33.49788459])]
 [array([ 65.02237223, -24.69813873]) array([ 64.96118709, -24.77757608])
  array([ 64.90000194, -24.85701343]) ...
  array([ 58.4143766 , -33.27737265]) array([ 58.35319145, -33.35681   ])
  array([ 58.29200631, -33.43624735])]
 [array([ 64.94234792, -24.63650148]) array([ 64.88116277, -24.71593884])
  array([ 64.81997763, -24.79537619]) ...
  array([ 58.33435229, -33.21573541]) array([ 58.27316714, -33.29517276])
  array([ 58.211982  , -33.37461011])]
 ...
 [array([ 57.34003806, -18.78096347]) array([ 57.27885292, -18.86040082])
  array([ 57.21766777, -18.93983818]) ...
  array([ 50.73204243, -27.36019739]) array([ 50.67085728, -27.43963475])
  array([ 50.60967214, -27.5190721 ])]
 [array([ 57.26001375, -18.71932623]) array([ 57.1988286 , -18.79876358])
  array([ 57.13764346, -18.87820093]) ...
  array([ 50.65201811, -27.29856015]) array([ 50.59083297, -27.3779975 ])
  array([ 50.52964782, -27.45743485])]
 [array([ 57.17998943, -18.65768899]) array([ 57.11880429, -18.73712634])
  array([ 57.05761914, -18.81656369]) ...
  array([ 50.5719938 , -27.23692291]) array([ 50.51080865, -27.31636026])
  array([ 50.44962351, -27.39579761])]]
3
(100, 100)
12.580630792789666
126
(100, 126)
33.79072413529735
338
(100, 338)
119
-106
[[array([ 65.0692078 , -24.68333624]) array([ 65.00919563, -24.76366342])
  array([ 64.94918347, -24.84399059]) ...
  array([ 58.52788207, -33.43899831]) array([ 58.46786991, -33.51932548])
  array([ 58.40785775, -33.59965266])]
 [array([ 64.98828708, -24.62288065]) array([ 64.92827492, -24.70320782])
  array([ 64.86826276, -24.783535  ]) ...
  array([ 58.44696136, -33.37854272]) array([ 58.3869492 , -33.45886989])
  array([ 58.32693703, -33.53919707])]
 [array([ 64.90736637, -24.56242506]) array([ 64.84735421, -24.64275223])
  array([ 64.78734204, -24.72307941]) ...
  array([ 58.36604064, -33.31808712]) array([ 58.30602848, -33.3984143 ])
  array([ 58.24601632, -33.47874147])]
 ...
 [array([ 57.21989863, -18.81914373]) array([ 57.15988647, -18.8994709 ])
  array([ 57.09987431, -18.97979808]) ...
  array([ 50.67857291, -27.5748058 ]) array([ 50.61856075, -27.65513297])
  array([ 50.55854858, -27.73546015])]
 [array([ 57.13897792, -18.75868814]) array([ 57.07896576, -18.83901531])
  array([ 57.0189536 , -18.91934249]) ...
  array([ 50.5976522, -27.5143502]) array([ 50.53764003, -27.59467738])
  array([ 50.47762787, -27.67500455])]
 [array([ 57.05805721, -18.69823254]) array([ 56.99804505, -18.77855972])
  array([ 56.93803288, -18.85888689]) ...
  array([ 50.51673148, -27.45389461]) array([ 50.45671932, -27.53422178])
  array([ 50.39670716, -27.61454896])]]
4
(100, 100)
12.792974638739892
128
(100, 128)
33.79072413529735
338
(100, 338)
119
-105
[[array([ 65.04064562, -24.65806331]) array([ 64.98125233, -24.73884915])
  array([ 64.92185904, -24.81963499]) ...
  array([ 58.50738353, -33.54450547]) array([ 58.44799023, -33.62529131])
  array([ 58.38859694, -33.70607714])]
 [array([ 64.95926286, -24.59823117]) array([ 64.89986956, -24.679017  ])
  array([ 64.84047627, -24.75980284]) ...
  array([ 58.42600076, -33.48467332]) array([ 58.36660747, -33.56545916])
  array([ 58.30721418, -33.64624499])]
 [array([ 64.87788009, -24.53839902]) array([ 64.8184868 , -24.61918485])
  array([ 64.75909351, -24.69997069]) ...
  array([ 58.344618  , -33.42484117]) array([ 58.2852247 , -33.50562701])
  array([ 58.22583141, -33.58641285])]
 ...
 [array([ 57.14651743, -18.85434484]) array([ 57.08712413, -18.93513068])
  array([ 57.02773084, -19.01591651]) ...
  array([ 50.61325533, -27.74078699]) array([ 50.55386204, -27.82157283])
  array([ 50.49446875, -27.90235867])]
 [array([ 57.06513466, -18.79451269]) array([ 57.00574137, -18.87529853])
  array([ 56.94634808, -18.95608436]) ...
  array([ 50.53187257, -27.68095484]) array([ 50.47247927, -27.76174068])
  array([ 50.41308598, -27.84252652])]
 [array([ 56.9837519 , -18.73468054]) array([ 56.9243586 , -18.81546638])
  array([ 56.86496531, -18.89625221]) ...
  array([ 50.4504898 , -27.62112269]) array([ 50.39109651, -27.70190853])
  array([ 50.33170322, -27.78269437])]]
5
(100, 100)
13.024218357295899
131
(100, 131)
33.79072413529735
338
(100, 338)
119
-103
[[array([ 65.01135928, -24.6422957 ]) array([ 64.95250568, -24.72347555])
  array([ 64.89365208, -24.80465541]) ...
  array([ 58.41975628, -33.73443933]) array([ 58.36090268, -33.81561918])
  array([ 58.30204909, -33.89679904])]
 [array([ 64.92957959, -24.58300723]) array([ 64.87072599, -24.66418709])
  array([ 64.81187239, -24.74536694]) ...
  array([ 58.33797659, -33.67515086]) array([ 58.27912299, -33.75633072])
  array([ 58.22026939, -33.83751057])]
 [array([ 64.84779989, -24.52371876]) array([ 64.7889463 , -24.60489862])
  array([ 64.7300927 , -24.68607847]) ...
  array([ 58.2561969, -33.6158624]) array([ 58.1973433 , -33.69704225])
  array([ 58.1384897, -33.7782221])]
 ...
 [array([ 57.07872912, -18.89131432]) array([ 57.01987552, -18.97249417])
  array([ 56.96102192, -19.05367403]) ...
  array([ 50.48712612, -27.98345795]) array([ 50.42827252, -28.0646378 ])
  array([ 50.36941893, -28.14581766])]
 [array([ 56.99694943, -18.83202585]) array([ 56.93809583, -18.9132057 ])
  array([ 56.87924223, -18.99438556]) ...
  array([ 50.40534643, -27.92416948]) array([ 50.34649283, -28.00534934])
  array([ 50.28763923, -28.08652919])]
 [array([ 56.91516973, -18.77273738]) array([ 56.85631614, -18.85391724])
  array([ 56.79746254, -18.93509709]) ...
  array([ 50.32356674, -27.86488101]) array([ 50.26471314, -27.94606087])
  array([ 50.20585954, -28.02724072])]]
6
(100, 100)
13.24326180306953
133
(100, 133)
33.79072413529735
338
(100, 338)
119
-102
[[array([ 64.97471394, -24.59305126]) array([ 64.91682458, -24.6749215 ])
  array([ 64.85893521, -24.75679174]) ...
  array([ 58.43321591, -33.84438848]) array([ 58.37532655, -33.92625872])
  array([ 58.31743719, -34.00812896])]
 [array([ 64.89223876, -24.53473415]) array([ 64.83434939, -24.61660439])
  array([ 64.77646003, -24.69847463]) ...
  array([ 58.35074073, -33.78607137]) array([ 58.29285137, -33.86794161])
  array([ 58.23496201, -33.94981185])]
 [array([ 64.80976358, -24.47641705]) array([ 64.75187421, -24.55828729])
  array([ 64.69398485, -24.64015753]) ...
  array([ 58.26826555, -33.72775426]) array([ 58.21037619, -33.8096245 ])
  array([ 58.15248683, -33.89149474])]
 ...
 [array([ 56.97462142, -18.93629179]) array([ 56.91673205, -19.01816203])
  array([ 56.85884269, -19.10003227]) ...
  array([ 50.43312339, -28.187629  ]) array([ 50.37523403, -28.26949925])
  array([ 50.31734466, -28.35136949])]
 [array([ 56.89214623, -18.87797468]) array([ 56.83425687, -18.95984492])
  array([ 56.77636751, -19.04171516]) ...
  array([ 50.35064821, -28.1293119 ]) array([ 50.29275885, -28.21118214])
  array([ 50.23486948, -28.29305238])]
 [array([ 56.80967105, -18.81965757]) array([ 56.75178169, -18.90152781])
  array([ 56.69389233, -18.98339805]) ...
  array([ 50.26817303, -28.07099479]) array([ 50.21028367, -28.15286503])
  array([ 50.1523943 , -28.23473527])]]
7
(100, 100)
13.48882852441624
135
(100, 135)
33.79072413529735
338
(100, 338)
119
-101
[[array([ 64.93256023, -24.52792728]) array([ 64.87586658, -24.61063003])
  array([ 64.81917292, -24.69333278]) ...
  array([ 58.46948374, -33.95604043]) array([ 58.41279009, -34.03874318])
  array([ 58.35609643, -34.12144593])]
 [array([ 64.84924639, -24.47081472]) array([ 64.79255274, -24.55351747])
  array([ 64.73585909, -24.63622021]) ...
  array([ 58.3861699 , -33.89892787]) array([ 58.32947625, -33.98163062])
  array([ 58.2727826 , -34.06433336])]
 [array([ 64.76593255, -24.41370216]) array([ 64.7092389, -24.4964049])
  array([ 64.65254525, -24.57910765]) ...
  array([ 58.30285606, -33.84181531]) array([ 58.24616241, -33.92451805])
  array([ 58.18946876, -34.0072208 ])]
 ...
 [array([ 56.85111793, -18.98800865]) array([ 56.79442428, -19.07071139])
  array([ 56.73773062, -19.15341414]) ...
  array([ 50.38804144, -28.4161218 ]) array([ 50.33134779, -28.49882455])
  array([ 50.27465413, -28.58152729])]
 [array([ 56.76780409, -18.93089608]) array([ 56.71111044, -19.01359883])
  array([ 56.65441679, -19.09630158]) ...
  array([ 50.3047276 , -28.35900924]) array([ 50.24803395, -28.44171198])
  array([ 50.1913403 , -28.52441473])]
 [array([ 56.68449025, -18.87378352]) array([ 56.6277966 , -18.95648627])
  array([ 56.57110295, -19.03918902]) ...
  array([ 50.22141376, -28.30189667]) array([ 50.16472011, -28.38459942])
  array([ 50.10802646, -28.46730217])]]
8
(100, 100)
13.766457026380767
138
(100, 138)
33.79072413529735
338
(100, 338)
119
-100
[[array([ 64.88127497, -24.43327471]) array([ 64.82618791, -24.51705615])
  array([ 64.77110086, -24.6008376 ]) ...
  array([ 58.54626334, -34.06814105]) array([ 58.49117628, -34.15192249])
  array([ 58.43608922, -34.23570394])]
 [array([ 64.79687446, -24.37778061]) array([ 64.74178741, -24.46156206])
  array([ 64.68670035, -24.5453435 ]) ...
  array([ 58.46186283, -34.01264695]) array([ 58.40677577, -34.0964284 ])
  array([ 58.35168872, -34.18020985])]
 [array([ 64.71247396, -24.32228651]) array([ 64.6573869 , -24.40606796])
  array([ 64.60229984, -24.48984941]) ...
  array([ 58.37746232, -33.95715286]) array([ 58.32237527, -34.0409343 ])
  array([ 58.26728821, -34.12471575])]
 ...
 [array([ 56.69442568, -19.05034736]) array([ 56.63933862, -19.13412881])
  array([ 56.58425156, -19.21791026]) ...
  array([ 50.35941405, -28.6852137 ]) array([ 50.30432699, -28.76899515])
  array([ 50.24923993, -28.8527766 ])]
 [array([ 56.61002517, -18.99485327]) array([ 56.55493811, -19.07863471])
  array([ 56.49985106, -19.16241616]) ...
  array([ 50.27501354, -28.62971961]) array([ 50.21992648, -28.71350105])
  array([ 50.16483942, -28.7972825 ])]
 [array([ 56.52562466, -18.93935917]) array([ 56.47053761, -19.02314062])
  array([ 56.41545055, -19.10692206]) ...
  array([ 50.19061303, -28.57422551]) array([ 50.13552597, -28.65800696])
  array([ 50.08043892, -28.7417884 ])]]
9
(100, 100)
14.011703120676462
141
(100, 141)
33.79072413529735
338
(100, 338)
119
-98
[[array([ 64.84098027, -24.40929562]) array([ 64.7866905 , -24.49359589])
  array([ 64.73240073, -24.57789616]) ...
  array([ 58.48907725, -34.27242729]) array([ 58.43478748, -34.35672756])
  array([ 58.38049771, -34.44102783])]
 [array([ 64.7560571 , -24.35460471]) array([ 64.70176733, -24.43890498])
  array([ 64.64747756, -24.52320525]) ...
  array([ 58.40415408, -34.21773637]) array([ 58.34986431, -34.30203664])
  array([ 58.29557454, -34.38633691])]
 [array([ 64.67113393, -24.29991379]) array([ 64.61684416, -24.38421406])
  array([ 64.5625544 , -24.46851433]) ...
  array([ 58.31923092, -34.16304546]) array([ 58.26494115, -34.24734573])
  array([ 58.21065138, -34.331646  ])]
 ...
 [array([ 56.60343317, -19.10427669]) array([ 56.5491434 , -19.18857696])
  array([ 56.49485363, -19.27287723]) ...
  array([ 50.25153015, -28.96740835]) array([ 50.19724038, -29.05170862])
  array([ 50.14295061, -29.13600889])]
 [array([ 56.51851   , -19.04958577]) array([ 56.46422023, -19.13388604])
  array([ 56.40993046, -19.21818631]) ...
  array([ 50.16660698, -28.91271743]) array([ 50.11231721, -28.9970177 ])
  array([ 50.05802744, -29.08131798])]
 [array([ 56.43358684, -18.99489485]) array([ 56.37929707, -19.07919512])
  array([ 56.3250073 , -19.16349539]) ...
  array([ 50.08168382, -28.85802652]) array([ 50.02739405, -28.94232679])
  array([ 49.97310428, -29.02662706])]]
10
(100, 100)
14.18972019286814
142
(100, 142)
33.79072413529735
338
(100, 338)
119
-98
[[array([ 64.80330712, -24.40561406]) array([ 64.74959441, -24.49028317])
  array([ 64.6958817 , -24.57495229]) ...
  array([ 58.51891975, -34.31190062]) array([ 58.46520704, -34.39656974])
  array([ 58.41149432, -34.48123886])]
 [array([ 64.71801238, -24.35150446]) array([ 64.66429967, -24.43617358])
  array([ 64.61058696, -24.52084269]) ...
  array([ 58.43362501, -34.25779103]) array([ 58.3799123 , -34.34246014])
  array([ 58.32619959, -34.42712926])]
 [array([ 64.63271765, -24.29739486]) array([ 64.57900494, -24.38206398])
  array([ 64.52529222, -24.4667331 ]) ...
  array([ 58.34833028, -34.20368143]) array([ 58.29461756, -34.28835055])
  array([ 58.24090485, -34.37301966])]
 ...
 [array([ 56.52971766, -19.15698322]) array([ 56.47600495, -19.24165234])
  array([ 56.42229224, -19.32632146]) ...
  array([ 50.24533029, -29.06326979]) array([ 50.19161758, -29.14793891])
  array([ 50.13790487, -29.23260803])]
 [array([ 56.44442293, -19.10287363]) array([ 56.39071021, -19.18754274])
  array([ 56.3369975 , -19.27221186]) ...
  array([ 50.16003556, -29.0091602 ]) array([ 50.10632284, -29.09382931])
  array([ 50.05261013, -29.17849843])]
 [array([ 56.35912819, -19.04876403]) array([ 56.30541548, -19.13343315])
  array([ 56.25170276, -19.21810226]) ...
  array([ 50.07474082, -28.9550506 ]) array([ 50.02102811, -29.03971972])
  array([ 49.96731539, -29.12438883])]]
11
(100, 100)
14.37053591230606
144
(100, 144)
33.79072413529735
338
(100, 338)
119
-97
[[array([ 64.75812979, -24.3753093 ]) array([ 64.70535289, -24.46056488])
  array([ 64.652576  , -24.54582046]) ...
  array([ 58.53045651, -34.43546803]) array([ 58.47767962, -34.52072361])
  array([ 58.42490273, -34.60597919])]
 [array([ 64.67224425, -24.32214244]) array([ 64.61946736, -24.40739802])
  array([ 64.56669046, -24.4926536 ]) ...
  array([ 58.44457097, -34.38230117]) array([ 58.39179408, -34.46755675])
  array([ 58.33901719, -34.55281233])]
 [array([ 64.58635871, -24.26897557]) array([ 64.53358182, -24.35423116])
  array([ 64.48080493, -24.43948674]) ...
  array([ 58.35868544, -34.32913431]) array([ 58.30590854, -34.41438989])
  array([ 58.25313165, -34.49964547])]
 ...
 [array([ 56.42723274, -19.21812378]) array([ 56.37445584, -19.30337936])
  array([ 56.32167895, -19.38863494]) ...
  array([ 50.19955946, -29.27828251]) array([ 50.14678257, -29.36353809])
  array([ 50.09400568, -29.44879368])]
 [array([ 56.3413472 , -19.16495692]) array([ 56.28857031, -19.2502125 ])
  array([ 56.23579341, -19.33546808]) ...
  array([ 50.11367392, -29.22511565]) array([ 50.06089703, -29.31037123])
  array([ 50.00812014, -29.39562682])]
 [array([ 56.25546166, -19.11179006]) array([ 56.20268477, -19.19704564])
  array([ 56.14990788, -19.28230122]) ...
  array([ 50.02778839, -29.17194879]) array([ 49.97501149, -29.25720437])
  array([ 49.9222346 , -29.34245995])]]
12
(100, 100)
14.605099900741404
147
(100, 147)
33.79072413529735
338
(100, 338)
119
-95
[[array([ 64.7185932 , -24.37901746]) array([ 64.66636572, -24.46461072])
  array([ 64.61413824, -24.55020397]) ...
  array([ 58.45129587, -34.65020804]) array([ 58.39906839, -34.73580129])
  array([ 58.34684092, -34.82139455])]
 [array([ 64.63236749, -24.32640408]) array([ 64.58014001, -24.41199733])
  array([ 64.52791254, -24.49759059]) ...
  array([ 58.36507017, -34.59759465]) array([ 58.31284269, -34.6831879 ])
  array([ 58.26061521, -34.76878116])]
 [array([ 64.54614179, -24.27379069]) array([ 64.49391431, -24.35938394])
  array([ 64.44168683, -24.4449772 ]) ...
  array([ 58.27884446, -34.54498126]) array([ 58.22661699, -34.63057452])
  array([ 58.17438951, -34.71616777])]
 ...
 [array([ 56.35469991, -19.27551893]) array([ 56.30247243, -19.36111219])
  array([ 56.25024496, -19.44670544]) ...
  array([ 50.08740259, -29.54670951]) array([ 50.03517511, -29.63230276])
  array([ 49.98294763, -29.71789602])]
 [array([ 56.26847421, -19.22290555]) array([ 56.21624673, -19.3084988 ])
  array([ 56.16401925, -19.39409205]) ...
  array([ 50.00117688, -29.49409612]) array([ 49.94894941, -29.57968937])
  array([ 49.89672193, -29.66528263])]
 [array([ 56.1822485 , -19.17029216]) array([ 56.13002103, -19.25588541])
  array([ 56.07779355, -19.34147867]) ...
  array([ 49.91495118, -29.44148273]) array([ 49.8627237 , -29.52707599])
  array([ 49.81049622, -29.61266924])]]
13
(100, 100)
14.900139337809037
150
(100, 150)
33.79072413529735
338
(100, 338)
119
-94
[[array([ 64.66890639, -24.35066017]) array([ 64.61767465, -24.43685311])
  array([ 64.5664429 , -24.52304605]) ...
  array([ 58.4698653, -34.780006 ]) array([ 58.41863356, -34.86619895])
  array([ 58.36740182, -34.95239189])]
 [array([ 64.58207657, -24.29904987]) array([ 64.53084483, -24.38524281])
  array([ 64.47961308, -24.47143575]) ...
  array([ 58.38303548, -34.72839571]) array([ 58.33180374, -34.81458865])
  array([ 58.28057199, -34.90078159])]
 [array([ 64.49524675, -24.24743957]) array([ 64.444015  , -24.33363252])
  array([ 64.39278326, -24.41982546]) ...
  array([ 58.29620566, -34.67678541]) array([ 58.24497392, -34.76297835])
  array([ 58.19374217, -34.84917129])]
 ...
 [array([ 56.24641375, -19.34446143]) array([ 56.195182  , -19.43065437])

In [18]:
time_series = np.array(time_series)

lengths = 5
widths = 2
resolution = 0.1

Y, X = time_series[0].shape
center_x, center_y = X // 2, Y // 2  # center the ellipse within your grid
length_x,length_y =  (2*widths)*(1/resolution),(lengths+widths)*(1/resolution)

start_x = center_x - int(length_x // 2)
end_x = center_x + int(length_x // 2)
start_y = center_y - int(length_y // 2)
end_y = center_y + int(length_y // 2)

# Create a 3D mask with the same shape as data_3d
mask_small = np.zeros((Y, X), dtype=bool)

# Set values inside the rectangle to True
mask_small[start_y:end_y, start_x:end_x] = True

risk_data_3d = np.zeros_like(time_series[0])
risk_data_3d[mask_small] = 1




# range_end = ((2*lengths) - (lengths+widths))*(1/resolution) 
range_end = int(len(time_series[0]))+1

# for i in range(0,int(range_end),1):

for i in range(0,range_end,1):

    length_x,length_y = (2*widths)*(1/resolution)+i,(lengths+widths)*(1/resolution)+i
    start_x = center_x - int(length_x // 2)
    end_x = center_x + int(length_x // 2)
    start_y = center_y - int(length_y // 2)
    end_y = center_y + int(length_y // 2)

    # Create a 3D mask with the same shape as data_3d
    mask_test_lower = np.zeros((Y, X), dtype=bool)

    # Set values inside the rectangle to True
    mask_test_lower[start_y:end_y, start_x:end_x] = True

    length_x,length_y = (2*widths)*(1/resolution)+i+1,(lengths+widths)*(1/resolution)+i+1
    start_x = center_x - int(length_x // 2)
    end_x = center_x + int(length_x // 2)
    start_y = center_y - int(length_y // 2)
    end_y = center_y + int(length_y // 2)

    # Create a 3D mask with the same shape as data_3d
    mask_test_upper = np.zeros((Y, X), dtype=bool)

    # Set values inside the rectangle to True
    mask_test_upper[start_y:end_y, start_x:end_x] = True


    risk_data_3d[np.logical_and(mask_test_upper, ~mask_test_lower)] = 1-i/range_end

risk_data_3d = risk_data_3d.astype(float) #heatmap risk

reversed_time_series=time_series[:,::-1, :] # locational based risk



# case 5 exponential method (Cox Model)
# risk_update = risk_basic at time t = 0
# Then it get updated after time t= 0

percent_change = []
for i in range(len(reversed_time_series)):
    if i ==0:
        row = np.ones_like(reversed_time_series[i]) # zero risk of collision
        percent_change.append(row)
    else:
        row = np.exp((reversed_time_series[i]-reversed_time_series[i-1]).astype(float))
        #row = np.multiply(row, percent_change[-1])
        #row = np.minimum(row,1)
        percent_change.append(row)

percent_change = np.array(percent_change)

risk_max_no_boost = []
risk_time_series =[]
vmax = 0

risk_max = []
risk_sum = []

risk_time_series_norm =[]

risk_max_norm = []
risk_sum_norm = []


a = 1/(10*10)







max_boost = np.exp(1)
for t in range(len(reversed_time_series)):

    result_temp = reversed_time_series[t]*risk_data_3d
    risk_max_no_boost.append(np.max(result_temp))

    result_temp = reversed_time_series[t]*risk_data_3d*percent_change[t]


    ############ FILTER only the values within the safety box #############
  
    ####################### HEREHREHREHRHERHEREH##################
    # Here we need to filter based on the index here:

    # This is the actual safety box we saw 

    ego_vehicle_position = (df_av1.iloc[int(t)]["position_x"], df_av1.iloc[int(t)]["position_y"])
    ego_vehicle_velocity = (df_av1.iloc[int(t)]["velocity_x"], df_av1.iloc[int(t)]["velocity_y"])
    ego_vehicle_car_angle = np.arctan2(df_av1.iloc[int(t)]["velocity_y"], df_av1.iloc[int(t)]["velocity_x"])# df_av1.iloc[int(time)]["heading"]

    heatmap = load_heatmap(t)  # Access preloaded heatmap
    #safety_box_corners_large, safety_box_array, safety_box_df,safety_box_array_distance, safety_box_df_distance = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity,ego_vehicle_car_angle)

    # original safety box
    safety_box_corners_large_og, safety_box_array_og, safety_box_df_og = fill_safety_box_with_occupancy_og(heatmap, *ego_vehicle_position, *ego_vehicle_velocity,ego_vehicle_car_angle)


    safety_box_corners_large, safety_box_array, safety_box_df = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity,ego_vehicle_car_angle)
    
    # maximum dynamical safety box  # Max safety_box based on the max velocity within the planned trajectory
    ego_vehicle_velocity_max = (np.max(abs(df_av1["velocity_x"])), np.max(abs(df_av1["velocity_y"])))
    #safety_box_corners_large_max, safety_box_array_max, safety_box_df_max,safety_box_array_distance_max, safety_box_df_distance_max = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity_max,ego_vehicle_car_angle)
    safety_box_corners_large_max, safety_box_array_max, safety_box_df_max = fill_safety_box_with_occupancy(heatmap, *ego_vehicle_position, *ego_vehicle_velocity_max,ego_vehicle_car_angle)

    

    ########################## Index based #################################

    result_temp_filter = result_temp[int((-safety_box_array_og.shape[1]+safety_box_array_max.shape[1])/2): int((-safety_box_array_max.shape[1]+safety_box_array.shape[1])/2)-1, :]



    ########################################################################

    #result = np.minimum(result_temp,1)
    if vmax <= np.max(result_temp_filter):
        vmax = np.max(result_temp_filter)
    #risk_time_series.append(result_temp)
    risk_max.append(np.max(result_temp_filter))
    #risk_sum.append(1-np.exp(-1*np.sum(result_temp)*a))

    #risk_time_series_norm.append(result_temp/max_boost)
    risk_max_norm.append(np.max(result_temp_filter/max_boost))
    print(np.max(result_temp_filter/max_boost))
    #risk_sum_norm.append(1-np.exp(-1*np.sum(result_temp/max_boost)*a))

(100, 100)
11.985315538192722
120
(100, 120)
33.79072413529735
338
(100, 338)
0.0735310264758872
(100, 100)
12.165318486700079
122
(100, 122)
33.79072413529735
338
(100, 338)
0.06171393819665207
(100, 100)
12.353613885764991
124
(100, 124)
33.79072413529735
338
(100, 338)
0.05602157481316786
(100, 100)
12.580630792789666
126
(100, 126)
33.79072413529735
338
(100, 338)
0.052278772320518994
(100, 100)
12.792974638739892
128
(100, 128)
33.79072413529735
338
(100, 338)
0.0475160071452942
(100, 100)
13.024218357295899
131
(100, 131)
33.79072413529735
338
(100, 338)
0.04944807780183067
(100, 100)
13.24326180306953
133
(100, 133)
33.79072413529735
338
(100, 338)
0.04174624042688612
(100, 100)
13.48882852441624
135
(100, 135)
33.79072413529735
338
(100, 338)
0.04201930568763042
(100, 100)
13.766457026380767
138
(100, 138)
33.79072413529735
338
(100, 338)
0.037385590635049065
(100, 100)
14.011703120676462
141
(100, 141)
33.79072413529735
338
(100, 338)
0.03564937814060619
(100, 100)
14.18972019286814
142
(100, 142)
33.79072413529735
338
(100, 338)
0.03252959234286617
(100, 100)
14.37053591230606
144
(100, 144)
33.79072413529735
338
(100, 338)
0.03061406921863042
(100, 100)
14.605099900741404
147
(100, 147)
33.79072413529735
338
(100, 338)
0.03297797115795401
(100, 100)
14.900139337809037
150
(100, 150)
33.79072413529735
338
(100, 338)
0.030010855933364174
(100, 100)
15.111117588914674
152
(100, 152)
33.79072413529735
338
(100, 338)
0.027686554470858774
(100, 100)
15.348638878588826
154
(100, 154)
33.79072413529735
338
(100, 338)
0.024773868754689087
(100, 100)
15.623091708689358
157
(100, 157)
33.79072413529735
338
(100, 338)
0.025583180726947347
(100, 100)
15.883586612601654
159
(100, 159)
33.79072413529735
338
(100, 338)
0.024379498303545355
(100, 100)
16.163990219958364
162
(100, 162)
33.79072413529735
338
(100, 338)
0.01665654643251834
(100, 100)
16.429338571725204
165
(100, 165)
33.79072413529735
338
(100, 338)
0.019239848303128197
(100, 100)
16.695591150504264
167
(100, 167)
33.79072413529735
338
(100, 338)
0.012613412617635484
(100, 100)
16.961637282116023
170
(100, 170)
33.79072413529735
338
(100, 338)
0.010779882875276255
(100, 100)
17.252973786161277
173
(100, 173)
33.79072413529735
338
(100, 338)
0.009810980681260684
(100, 100)
17.566000948502563
176
(100, 176)
33.79072413529735
338
(100, 338)
0.006009423988768867
(100, 100)
17.862977213569682
179
(100, 179)
33.79072413529735
338
(100, 338)
0.003381431987486102
(100, 100)
18.21283835880616
183
(100, 183)
33.79072413529735
338
(100, 338)
0.0015551640330137696
(100, 100)
18.5185496277574
186
(100, 186)
33.79072413529735
338
(100, 338)
0.0011319562863867
(100, 100)
18.87752560377671
189
(100, 189)
33.79072413529735
338
(100, 338)
0.000787566915355677
(100, 100)
19.21366066851106
193
(100, 193)
33.79072413529735
338
(100, 338)
0.00043294357552467396
(100, 100)
19.533475676389493
196
(100, 196)
33.79072413529735
338
(100, 338)
0.0002190711611091554
(100, 100)
19.823429626090313
199
(100, 199)
33.79072413529735
338
(100, 338)
0.00030131238718856537
(100, 100)
20.089064908171096
201
(100, 201)
33.79072413529735
338
(100, 338)
0.00013995135213226438
(100, 100)
20.365069627687433
204
(100, 204)
33.79072413529735
338
(100, 338)
0.00011526037055359184
(100, 100)
20.60038711597376
207
(100, 207)
33.79072413529735
338
(100, 338)
5.68378298924299e-05
(100, 100)
20.87320754924854
209
(100, 209)
33.79072413529735
338
(100, 338)
1.745334237272786e-05
(100, 100)
21.13675222728926
212
(100, 212)
33.79072413529735
338
(100, 338)
1.0375848991836627e-05
(100, 100)
21.360405977184172
214
(100, 214)
33.79072413529735
338
(100, 338)
3.322833162634641e-06
(100, 100)
21.60347667515551
217
(100, 217)
33.79072413529735
338
(100, 338)
2.016267947946965e-06
(100, 100)
21.858544844331522
219
(100, 219)
33.79072413529735
338
(100, 338)
2.3152949813361056e-06
(100, 100)
22.14736638460596
222
(100, 222)
33.79072413529735
338
(100, 338)
1.0470760066122467e-06
(100, 100)
22.413042291646686
225
(100, 225)
33.79072413529735
338
(100, 338)
5.792817182933955e-07
(100, 100)
22.714108919364882
228
(100, 228)
33.79072413529735
338
(100, 338)
3.739613365913857e-07
(100, 100)
22.996940623465683
230
(100, 230)
33.79072413529735
338
(100, 338)
2.0602136837751986e-07
(100, 100)
23.287119270899385
233
(100, 233)
33.79072413529735
338
(100, 338)
5.013518464421319e-07
(100, 100)
23.585034155141553
236
(100, 236)
33.79072413529735
338
(100, 338)
7.49633239942393e-07
(100, 100)
23.864432160121552
239
(100, 239)
33.79072413529735
338
(100, 338)
2.321377323601356e-06
(100, 100)
24.062462495385
241
(100, 241)
33.79072413529735
338
(100, 338)
4.194283340034588e-06
(100, 100)
24.380729076726805
244
(100, 244)
33.79072413529735
338
(100, 338)
6.126315018674081e-06
(100, 100)
24.879802688059677
249
(100, 249)
33.79072413529735
338
(100, 338)
9.341885536936543e-06
(100, 100)
25.245598612702373
253
(100, 253)
33.79072413529735
338
(100, 338)
1.669656255392829e-05
(100, 100)
25.538631454073947
256
(100, 256)
33.79072413529735
338
(100, 338)
3.4124132987438004e-05
(100, 100)
25.894852189080446
259
(100, 259)
33.79072413529735
338
(100, 338)
0.00023928713217803016
(100, 100)
26.14020412180001
262
(100, 262)
33.79072413529735
338
(100, 338)
0.0006685202167749727
(100, 100)
26.366403110814655
264
(100, 264)
33.79072413529735
338
(100, 338)
0.0005352054615974071
(100, 100)
26.604519151941805
267
(100, 267)
33.79072413529735
338
(100, 338)
0.0006517093049823052
(100, 100)
26.901680795082562
270
(100, 270)
33.79072413529735
338
(100, 338)
0.0022934141426809505
(100, 100)
27.191182736626494
272
(100, 272)
33.79072413529735
338
(100, 338)
0.003356773476737247
(100, 100)
27.450606488646343
275
(100, 275)
33.79072413529735
338
(100, 338)
0.008019119446731048
(100, 100)
27.660601506599722
277
(100, 277)
33.79072413529735
338
(100, 338)
0.007820641416743882
(100, 100)
27.890630670446672
279
(100, 279)
33.79072413529735
338
(100, 338)
0.02413189058979919
(100, 100)
28.264730655347336
283
(100, 283)
33.79072413529735
338
(100, 338)
0.039031953877973695
(100, 100)
28.515660829842
286
(100, 286)
33.79072413529735
338
(100, 338)
0.036788703208745444
(100, 100)
28.813033472142585
289
(100, 289)
33.79072413529735
338
(100, 338)
0.03750499036032729
(100, 100)
29.072795566150766
291
(100, 291)
33.79072413529735
338
(100, 338)
0.038970263926813804
(100, 100)
29.321632367204245
294
(100, 294)
33.79072413529735
338
(100, 338)
0.039256961359197866
(100, 100)
29.636893754249698
297
(100, 297)
33.79072413529735
338
(100, 338)
0.03981409339600316
(100, 100)
29.918693746738008
300
(100, 300)
33.79072413529735
338
(100, 338)
0.046918511976639654
(100, 100)
30.152616161650876
302
(100, 302)
33.79072413529735
338
(100, 338)
0.06456004124704125
(100, 100)
30.404504847019282
305
(100, 305)
33.79072413529735
338
(100, 338)
0.06620757999046585
(100, 100)
30.610910586613635
307
(100, 307)
33.79072413529735
338
(100, 338)
0.05078175330846405
(100, 100)
30.86447129896617
309
(100, 309)
33.79072413529735
338
(100, 338)
0.06520681625659658
(100, 100)
31.0730581175338
311
(100, 311)
33.79072413529735
338
(100, 338)
0.05917249971231242
(100, 100)
31.26117024705166
313
(100, 313)
33.79072413529735
338
(100, 338)
0.059523347067961634
(100, 100)
31.371015426705466
314
(100, 314)
33.79072413529735
338
(100, 338)
0.06184611363839778
(100, 100)
31.461646494811156
315
(100, 315)
33.79072413529735
338
(100, 338)
0.05729827750469696
(100, 100)
31.723358173282598
318
(100, 318)
33.79072413529735
338
(100, 338)
0.057669754080263744
(100, 100)
31.77961809217804
318
(100, 318)
33.79072413529735
338
(100, 338)
0.055879420411294733
(100, 100)
31.77896454669941
318
(100, 318)
33.79072413529735
338
(100, 338)
0.052390379187315594
(100, 100)
31.772125153899697
318
(100, 318)
33.79072413529735
338
(100, 338)
0.053030195230138494
(100, 100)
31.778300123726627
318
(100, 318)
33.79072413529735
338
(100, 338)
0.0523890776252367
(100, 100)
31.754630683406965
318
(100, 318)
33.79072413529735
338
(100, 338)
0.052089124413655555
(100, 100)
31.794745080193092
318
(100, 318)
33.79072413529735
338
(100, 338)
0.052205174597731455
(100, 100)
31.771548305713026
318
(100, 318)
33.79072413529735
338
(100, 338)
0.05274614347502524
(100, 100)
31.77654735972059
318
(100, 318)
33.79072413529735
338
(100, 338)
0.0518225965642775
(100, 100)
31.728550469595746
318
(100, 318)
33.79072413529735
338
(100, 338)
0.0512271502864295
(100, 100)
31.7058362988122
318
(100, 318)
33.79072413529735
338
(100, 338)
0.05129377598402893
(100, 100)
31.476357020104345
315
(100, 315)
33.79072413529735
338
(100, 338)
0.047578202651543104
(100, 100)
31.416681645857178
315
(100, 315)
33.79072413529735
338
(100, 338)
0.04670252265393081
(100, 100)
31.32904935069913
314
(100, 314)
33.79072413529735
338
(100, 338)
0.04412181841703835
(100, 100)
31.28501415378861
313
(100, 313)
33.79072413529735
338
(100, 338)
0.04399730783440171
(100, 100)
31.329003874813647
314
(100, 314)
33.79072413529735
338
(100, 338)
0.04280835096516286
(100, 100)
31.320490692978343
314
(100, 314)
33.79072413529735
338
(100, 338)
0.041232655450909435
(100, 100)
31.35086178071064
314
(100, 314)
33.79072413529735
338
(100, 338)
0.04108753334416824
(100, 100)
31.49137428254464
315
(100, 315)
33.79072413529735
338
(100, 338)
0.04225234237814072
(100, 100)
31.520082420964464
316
(100, 316)
33.79072413529735
338
(100, 338)
0.04255081821701546
(100, 100)
31.622910996809885
317
(100, 317)
33.79072413529735
338
(100, 338)
0.04368368361538737
(100, 100)
31.62178919849788
317
(100, 317)
33.79072413529735
338
(100, 338)
0.04444043779070726
(100, 100)
31.66017507386927
317
(100, 317)
33.79072413529735
338
(100, 338)
0.04193346023024976
(100, 100)
31.355624799824884
314
(100, 314)
33.79072413529735
338
(100, 338)
0.036424332648891444

In [19]:
plt.figure(figsize=(8, 5))
plt.plot(range(len(risk_max_norm)),np.array(risk_max_norm))
plt.savefig("PORA_Ex.png", dpi=300)

In [20]:
for i in range(len(risk_max_norm)):
    print(i)
    print(risk_max_norm[i])

0
0.0735310264758872
1
0.06171393819665207
2
0.05602157481316786
3
0.052278772320518994
4
0.0475160071452942
5
0.04944807780183067
6
0.04174624042688612
7
0.04201930568763042
8
0.037385590635049065
9
0.03564937814060619
10
0.03252959234286617
11
0.03061406921863042
12
0.03297797115795401
13
0.030010855933364174
14
0.027686554470858774
15
0.024773868754689087
16
0.025583180726947347
17
0.024379498303545355
18
0.01665654643251834
19
0.019239848303128197
20
0.012613412617635484
21
0.010779882875276255
22
0.009810980681260684
23
0.006009423988768867
24
0.003381431987486102
25
0.0015551640330137696
26
0.0011319562863867
27
0.000787566915355677
28
0.00043294357552467396
29
0.0002190711611091554
30
0.00030131238718856537
31
0.00013995135213226438
32
0.00011526037055359184
33
5.68378298924299e-05
34
1.745334237272786e-05
35
1.0375848991836627e-05
36
3.322833162634641e-06
37
2.016267947946965e-06
38
2.3152949813361056e-06
39
1.0470760066122467e-06
40
5.792817182933955e-07
41
3.739613365913857e-07
42
2.0602136837751986e-07
43
5.013518464421319e-07
44
7.49633239942393e-07
45
2.321377323601356e-06
46
4.194283340034588e-06
47
6.126315018674081e-06
48
9.341885536936543e-06
49
1.669656255392829e-05
50
3.4124132987438004e-05
51
0.00023928713217803016
52
0.0006685202167749727
53
0.0005352054615974071
54
0.0006517093049823052
55
0.0022934141426809505
56
0.003356773476737247
57
0.008019119446731048
58
0.007820641416743882
59
0.02413189058979919
60
0.039031953877973695
61
0.036788703208745444
62
0.03750499036032729
63
0.038970263926813804
64
0.039256961359197866
65
0.03981409339600316
66
0.046918511976639654
67
0.06456004124704125
68
0.06620757999046585
69
0.05078175330846405
70
0.06520681625659658
71
0.05917249971231242
72
0.059523347067961634
73
0.06184611363839778
74
0.05729827750469696
75
0.057669754080263744
76
0.055879420411294733
77
0.052390379187315594
78
0.053030195230138494
79
0.0523890776252367
80
0.052089124413655555
81
0.052205174597731455
82
0.05274614347502524
83
0.0518225965642775
84
0.0512271502864295
85
0.05129377598402893
86
0.047578202651543104
87
0.04670252265393081
88
0.04412181841703835
89
0.04399730783440171
90
0.04280835096516286
91
0.041232655450909435
92
0.04108753334416824
93
0.04225234237814072
94
0.04255081821701546
95
0.04368368361538737
96
0.04444043779070726
97
0.04193346023024976
98
0.036424332648891444